Iter15 commit 1 goroutines
trickychubakka/logger pull request #17
Opened 2024-11-28 18:10 UTC by trickychubakka

Iter15 commit 1 goroutines

2024-12-03 04:13 UTC, bulbetski requested changes

2024-12-03 04:13 UTC, bulbetski commented on cmd/server/main.go
>  		os.Exit(1)
Можно заменить на log.Fatal

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
Все горутины (metricsPolling, gopsMetricsPolling, metricsReport) используют один и тот же мьютекс для доступа к myMetrics. Таким образом выполнение одной горутины блокирует доступ остальных.  Нужно использовать канал для коммуникации между горутинами вместо мьютекса. Это улучшит производительность и упростит управление потоками

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
>  			log.Panicf("%s", errors.Unwrap(err))
Ошибки в горутинах приводят к вызову log.Panicf, что завершает всю программу. Это делает приложение менее устойчивым к отдельным сбоям.  Вместо panic использовать обработку ошибок с возможностью перезапуска или логирования для анализа.

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
> +func run(myMetrics internal.MetricsStorage, config *conf.AgentConfig) {
Функция run вызывает горутины напрямую и не предоставляет механизма управления ими. Это затрудняет завершение работы горутин при остановке программы.

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
> +func run(myMetrics internal.MetricsStorage, config *conf.AgentConfig) {
Горутины metricsPolling, gopsMetricsPolling, и metricsReport продолжают работать, даже если приложение завершено через сигнал.

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
Чтобы избежать передачи множества параметров в функции (хранилище, мьютексы, конфигурации), можно инкапсулировать их в структуры. Это улучшает читаемость, упрощает модификации и повышает тестируемость.

2024-12-03 04:13 UTC, bulbetski commented on cmd/agent/main.go
Разделение кода в main.go на отдельные модули и файлы делает проект более структурированным, читаемым и поддерживаемым. Вот пример того, как можно разделить код:

Можно сделать что-то подобное
```
project/
│
├── internal/
│   ├── metrics/
│   │   ├── polling.go          // Логика сбора метрик
│   │   ├── reporting.go        // Логика отправки метрик
│   │   ├── storage.go          // Хранилище метрик
│   │   └── gopsutil.go         // Работа с gopsutil
│   └── config/
│       ├── config.go           // Логика работы с конфигурацией
│       └── types.go            // Структуры конфигурации
│
├── cmd/
│   ├── agent/
│   │   ├── main.go             // Основная точка входа
│   │   ├── run.go              // Запуск всех горутин
│   │   └── shutdown.go         // Graceful shutdown
│
└── go.mod
```

2024-12-10 09:53 UTC, bulbetski requested changes
.

2024-12-16 11:54 UTC, trickychubakka commented on cmd/agent/flags.go
> +	}
да, но есть нюанс.
Этот блок кода -- однотипный, подобных операций в flags.go -- еще 3 блока. Смысл их одинаков (проверка одной из нескольких переменных окружения), поэтому везде используется одинаковый вид  if c, err := strconv.Atoi  с одной и той же переменной "с" с инициализацией по месту использования.  И такой формат, что принят мною, оставляет временную переменную "с" исключительно в области видимости условного оператора и она не может случайным образом повлиять на несколько других блоков -- подобная ошибка может быть неочевидной. Собственно, так я сделал после какой-то подобной проблемы при отладке.

2024-12-16 15:03 UTC, trickychubakka commented on cmd/agent/main.go
> +			log.Println("error in metricsPolling :", err)
Это встроенный go log -- там нет уровней.

2024-12-16 15:20 UTC, trickychubakka commented on cmd/agent/main.go
Они должны блокировать друг друга, потому что они выполняются строго по очереди над одним и тем же объектом метрик:
сначала раз в PollInterval секунд формируется объект ВСЕХ метрик Metrics путем заполнения его простыми метрикам (metricsPolling) и gops метриками (gopsMetricsPolling).
потом именно этот объект (который полдностью заполнен всеми 30-ю с лишним метриками) раз в ReportInterval секунд одним "батчом" отсылается горутиной metricsReport
Они все последовательно работают с одним и тем же объектом в памяти -- сначала его заполняют, потом отсылают. Параллельно эти горутины работать не должны -- здесь нет поштучного формирования метрики и отсылки метрик по одной на сервер (напомню нашу дискуссию по этому поводу), здесь последовательно заполняется один батч и после этого выкидывается на сервер.

2024-12-16 17:00 UTC, trickychubakka commented on cmd/agent/main.go
>> Чтобы избежать передачи множества параметров в функции (хранилище, мьютексы, конфигурации), можно инкапсулировать их в структуры.
Обсуждали с ревьювером на предыдущих ревью. Я предполагал подобный подход -- упаковку этих параметров и/или объектов в контейнеры и передачу в функции не длинного набора параметров, а одного контейнера с описанной структурой. Но по результатам обсуждения решили, что при небольшом количестве параметров для прозрачности лучше передавать их явно и напрямую, а не инкапсулируя их в контейнер, т.к. это снижает прозрачность.

2024-12-17 00:48 UTC, trickychubakka commented on cmd/agent/main.go
Вынес из agent/main.go в run.go логику работы горутин.
storage уже вынесены -- по разным типам storage

2024-12-23 14:35 UTC, bulbetski approved these changes
Апрув

2025-01-17 08:35 UTC, merged